server.shutdown: graceful
database.connection:
  username: ${DATABASE_USERNAME:empty-username}
  password: ${DATABASE_PASSWORD:empty-password}
publisher:
  bootstrapServers: "${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
  topic: ${KAFKA_TOPIC:domainEvents}
spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRE_URL:localhost}:${POSTGRE_PORT:5432}/course_database"
    username: course_username
    password: ${POSTGRE_PASSWORD:course_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  lifecycle:
    timeout-per-shutdown-phase: 10s